include:
  - path:
      - starter-kit-lsaai-mock/docker-compose.yaml
      - lsaai-mock.override.yml
    project_directory: starter-kit-lsaai-mock
    # env_file: 

  - path:
    - starter-kit-rems/docker-compose.yml
    - rems.override.yml

  - path:
    - starter-kit-storage-and-interfaces/docker-compose.yml
    - sda.override.yml
    project_directory: starter-kit-storage-and-interfaces
    env_file:
      - ../configuration/sda/.env

networks:
  #for all services
