services:
  # Create a JWK pair for GA4GH visas
  # This replaces the imperative: python generate_jwks.py
  rems-jwk-init: #TODO replace by a secrets block
    image: python:3.12-slim
    working_dir: /keys
    volumes: 
      - ./generate_jwks.py:/keys/generate_jwks.py:ro
      - ../configuration/rems/keys:/keys
    entrypoint:
      - sh
      - -c
      - |
        set -e
        if [ ! -s /keys/private-key.jwk ]; then
          pip install "Authlib>=1.2.0"
          python3 generate_jwks.py
        fi
    restart: "no"

  # Initialise the database
  # This replaces the imperative: docker-compose run --rm -e CMD="migrate" app
  rems-migrate:
    extends:
      file: ./docker-compose.yml
      service: app
    container_name: rems_migrate
    environment:
      - CMD=migrate
    ports: []
    restart: "no"
    volumes: #TODO make this DRY
      - ../configuration/rems/config.edn:/rems/config/config.edn
      - ../configuration/rems/keys/private-key.jwk:/rems/keys/private-key.jwk
      - ../configuration/rems/keys/public-key.jwk:/rems/keys/public-key.jwk
    networks:
      - rems-network

  app:
    depends_on:
      rems-jwk-init:
        condition: service_completed_successfully
      rems-migrate:
        condition: service_completed_successfully
    volumes:
      - ../configuration/rems/config.edn:/rems/config/config.edn
      - ../configuration/rems/keys/private-key.jwk:/rems/keys/private-key.jwk
      - ../configuration/rems/keys/public-key.jwk:/rems/keys/public-key.jwk
    networks:
      - lsaaimock
      - rems-network

  db:
    networks:
      - rems-network

networks:
  rems-network: